apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 685733152537.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 685733152537.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: aa73a93c
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
